//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2d.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int FCode { get; set; }
        public Nullable<System.DateTime> FlyDate { get; set; }
        public string Pass_Name { get; set; }
        public string Addr { get; set; }
        public string Phone { get; set; }
        public string Class { get; set; }
        public string Seatno { get; set; }
        public string CrdtNo { get; set; }
        public Nullable<decimal> Fare { get; set; }
    }
}
