//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2d.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int FCode { get; set; }
        public string FName { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public Nullable<System.TimeSpan> Arrival { get; set; }
        public Nullable<System.TimeSpan> Departure { get; set; }
        public Nullable<int> Exe_Seats { get; set; }
        public Nullable<decimal> Exe_Fare { get; set; }
        public Nullable<int> Eco_Seats { get; set; }
        public Nullable<decimal> Eco_Fare { get; set; }
        public Nullable<int> Bus_Seats { get; set; }
        public Nullable<decimal> Bus_Fare { get; set; }
    }
}
